// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUrATL8eB2UYfb_kH884yceYL4-48sv18',
    appId: '1:523290422820:web:cc65c166dabafca6bfb2b1',
    messagingSenderId: '523290422820',
    projectId: 'wicmic-71b1e',
    authDomain: 'wicmic-71b1e.firebaseapp.com',
    databaseURL: 'https://wicmic-71b1e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wicmic-71b1e.firebasestorage.app',
    measurementId: 'G-68DK8MFVCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu5_oXUXvURkIOHue5RFM4Jl-9lk9UkWc',
    appId: '1:523290422820:android:fba1f9dd0d1d4936bfb2b1',
    messagingSenderId: '523290422820',
    projectId: 'wicmic-71b1e',
    databaseURL: 'https://wicmic-71b1e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wicmic-71b1e.firebasestorage.app',
  );

}